# Google Credentials
PROJECT_ID: # GCP Project ID
SERVICE_ACCOUNT: # GCP Service Account
JSON_KEY_FILE: # Full path of GCP JSON key

# Google Storage
DATA_BUCKET: # GCP Storage Bucket

# Data File Names
FULL_DATASET_NAME: S&P_500_Full_Stock_Data.csv # Default Dataset Name Uploaded to GCP